### ISSUE TITLE
[Feature request] Support the experimental <script setup> feature

### ISSUE THREAD

**Issue by mehcode** [vuedx/languagetools#112]
**Is your feature request related to a problem? Please describe.**

When using the experimental `<script setup>` feature in the Vue 3.0.4, the context is not set correctly when checking types in the `template`.

```
=> ./src/App.vue:3:4
Error :: Cannot find name 'SiteFooter'. (code 2304)
```

```vue
<template>
  <router-view class="flex-1" />
  <SiteFooter />
</template>

<script lang="ts" setup>
import SiteFooter from "./components/SiteFooter.vue";
</script>
```

**Describe the solution you'd like**

The Vue type support should handle the implicit `setup()` wrapping.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by znck** [comment]
There is partial support for `<script setup>`. I'll wait for https://github.com/vuejs/rfcs/pull/227 to reach the final comments stage before further implementation.

**Comment by dhruvkelawala** [comment]
I wish <script setup> was supported sooner. So far, I love the [vuejs/rfcs#227](https://github.com/vuejs/rfcs/pull/227) and wished I would be able to use it with this extension. Currently it throws so many errors, that I would have to make choice of one over the other.
