### ISSUE TITLE
Built-in event pass-through on on custom components

### ISSUE THREAD

**Issue by mehcode** [vuedx/languagetools#115]
**Describe the bug**

Attempting to use a built-in event (e.g., `@click`) on a custom-component produces a type error indicating that the custom component does not have an `onClick` prop – which is true, however Vue 3 passes through events transparently so this should type-check fine.

```
=> ./src/components/MainDrawer.vue:8:61
Error :: Type '{ icon: string; text: string; onClick: () => void; }' is not assignable to type 'IntrinsicAttributes & Partial<{ activeIcon: string; href: string; to: RouteLocationRaw; }> & Pick<Readonly<{ text: string; icon: string; activeIcon: string; href: string; to: RouteLocationRaw; } & {}> & VNodeProps & AllowedComponentProps & ComponentCustomProps, "key" | ... 10 more ... | "icon">'.
      -> Property 'onClick' does not exist on type 'IntrinsicAttributes & Partial<{ activeIcon: string; href: string; to: RouteLocationRaw; }> & Pick<Readonly<{ text: string; icon: string; activeIcon: string; href: string; to: RouteLocationRaw; } & {}> & VNodeProps & AllowedComponentProps & ComponentCustomProps, "key" | ... 10 more ... | "icon">'. (code 2322)
   6 |     <div class="flex-1" />
   7 |     <div class="p-5">
   8 |       <MainNavItem :icon="iconNavGreyTools" text="Log Out" @click="logOut" />
     |                                                             ^^^^^^^
   9 |     </div>
  10 |   </div>
```

**To Reproduce**

Given a component `MyComponent` that does *not* define an `onClick` custom event or prop:

```vue
<MyComponent @click="myHandler">
```

**Expected behavior**

No type error. Using built-in events on custom components is okay in Vue 3.

**Screenshots/Recording**

N/A

**Info (please complete the following information):**
 - OS Mac
 - IDE VS Code
 - TypeScript Version 4.1

**Additional context**

N/A

**Comment by znck** [comment]
Pass-through only works when using a single HTML root node, allowing by default is not expected behavior.

**Comment by elevatebart** [comment]
@znck could you detect if the targeted component has multiple heads?

**Comment by elevatebart** [comment]
@mehcode an alternative could be to define the click event on your customized component.
It is more code to write, but has some advantages:
- Makes it clear which events you allow in your custom component (especially if you do not cover touch or hover)
- Allows you to make sure each event is actually working so that your functional coverage is done

Downside: If you want to hack a new event on a library that did not explicitly implement it, you are stuck.

**Comment by znck** [comment]
Yes, it's possible to detect multiple roots. 

You can use Typescript's definition merging to extend JSX namespace for adding additional props to 3rd party components.

**Comment by mehcode** [comment]
How about supporting explicit attribute inheritance: https://v3.vuejs.org/guide/component-attrs.html#disabling-attribute-inheritance

In other words, require `v-bind="$attrs"` on the root node to opt-in to attribute inheritance for the purpose of type checking?

**Comment by elevatebart** [comment]
Additionally, on version 0.6.3 one cannot define custom events in a vue file. 

```vue
<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  name: "MyButton",
  emits: ["press"],
});
</script>

<template>
  <button @click="$emit('press')">
    <slot />
  </button>
</template>
```

and usage 

```vue
<script lang="ts">
import { defineComponent } from "vue";
import MyButton from './component/MyButton.vue'

export default defineComponent({
  name: "MyApp",
  components: { MyButton },
  setup(){
    function handlePress(){
      console.log("button clicked !!")
    }
    return { handlePress }
  }
});
</script>

<template>
  <div>
    <MyButton @press="handlePress" />
  </div>
</template>
```

On the template of `MyApp` I still get the red squiggles of death.

Am I doing something wrong here?

Note: the workaround is to use `// @ts-ignore` every time you use an event.

**Comment by softboy99** [comment]
I have same problem

**Comment by richardtallent** [comment]
Same issue here. My component has a single DIV root, but I'm getting an error attaching a `@click` handler to instances of the component.

**Comment by b12f** [comment]
I feel like the same should apply for [inherited attributes](https://v3.vuejs.org/guide/component-attrs.html#attribute-inheritance). 

```
// CustomButton does not have `type` or `onClick` as props
<CustomButton
  type="button"
  onClick={callback}
>Click me </CustomButton>
```

I feel the above should work fine. If setting an unknown attribute, just a warning or no action at all should be fine. If using a known prop, type checking should kick in.

**Comment by b12f** [comment]
@znck I feel like this issue is important enough to keep open, no?

**Comment by znck** [comment]
It's already supported in the latest prerelease build. There are some issues with inheritAttrs but it's on my todo list.

**Comment by b12f** [comment]
All right thanks a lot!
