### ISSUE TITLE
$refs not recognized

### ISSUE THREAD

**Issue by selfagency** [vuedx/languagetools#124]
**Describe the bug**
The Vue `$refs` object is not recognized as valid by the parser, which says `Property '$refs' does not exist on type`.

**To Reproduce**
1. Use `this.$refs` in a method.

**Expected behavior**
All of Vues internals should be recognized

**Screenshots/Recording**
![image](https://user-images.githubusercontent.com/2541728/103310670-29f28f00-49e6-11eb-94d3-c4033f95e280.png)

**Info (please complete the following information):**
 - OS: MacOS 11.1
 - IDE: VS Code Insiders
 - TypeScript Version: N/A

**Comment by znck** [comment]
Please provide a small code sample. If you could, you can send a PR to add a new file with this issue in [samples/feature-diagnostics](https://github.com/znck/vue-developer-experience/tree/master/samples/feature-diagnostics) directory.

**Comment by selfagency** [comment]
closing this because it's 2 years old and i want to clean up my issues tab
