### ISSUE TITLE
SFC syntax highlighting issue

### ISSUE THREAD

**Issue by 1isten** [vuedx/languagetools#137]
SFC lost some syntax highlighting after I install and enable the  vue extension: https://marketplace.visualstudio.com/items?itemName=znck.vue

Notably the `<template>`, `<script>`, `v-show`, etc

<img width="509" alt="issue" src="https://user-images.githubusercontent.com/11518941/103433566-1174b580-4c2e-11eb-8f04-626105d773b2.png">

**Comment by znck** [comment]
Blocks `<script>`, `<template>` and `<style>` are intentionally un-highlighted.

Will fix `v-show`.

**Comment by eladcandroid** [comment]
> Blocks `<script>`, `<template>` and `<style>` are intentionally un-highlighted.

Why?
