### ISSUE TITLE
Template type checking not working with Vue 2

### ISSUE THREAD

**Issue by benrwb** [vuedx/languagetools#138]
**Describe the bug**
Template type checking doesn't work in Vue 2 project. (But it works fine in Vue 3 project).

**To Reproduce**
1. Create new empty folder
2. Install vue types `npm install vue`
2. Add basic tsconfig.json file
```
{
    "compilerOptions": {
        "noImplicitThis": true,
        "noImplicitAny": true
    }
}
```
3. Create MyComponent.vue
```
<template>
    <div>Hello {{ name }}</div>
</template>

<script lang="ts">
    import Vue from 'vue';

    export default Vue.extend({
        data: function () {
            return {
                name: "test"
            }
        }
    })
</script>
```

**Expected behavior**
When I hover over `{{ name }}` in the template, I expect to see `var name: string`. But what actually appears is `var name: any`. When I select `{{ name }}` and press F12, it says `"No definition found for name"`

**Screenshots/Recording**
![vue 2 vs 3](https://user-images.githubusercontent.com/4542676/103454864-e5b20800-4cdf-11eb-9a18-1d66127029ad.png)

**Info (please complete the following information):**
 - OS = Windows 10
 - IDE = VS Code
 - TypeScript Version = 3.4.5
 - Vue Version = 2.6.12 / 3.0.5
 - VueDX version = 0.4.1

**Additional context**
N/A

**Comment by armano2** [comment]
Small information about this issue:

this seem to be an issue only if `Vue.extend` is used, but in case of default object export it seem to be working.

![image](https://user-images.githubusercontent.com/625469/104514680-eefd7780-55f1-11eb-80c1-1fe802bee562.png)
![image](https://user-images.githubusercontent.com/625469/104514711-fc1a6680-55f1-11eb-919d-beadcf6cbd6c.png)

**Comment by znck** [comment]
Class components and composition-api plugin are not supported yet.

**Comment by Rokuem** [comment]
@znck do we have an issue to track the support for the composition-api plugin in vueDX? I also tried to use that but seems like it gives a type error for the whole component.

**Comment by znck** [comment]
I have been away for a while, I'll catch up and fix this in May.
