### ISSUE TITLE
Syntax Highlight breaks Bracket Pair Colorizer 2

### ISSUE THREAD

**Issue by eladcandroid** [vuedx/languagetools#141]
1. Try to install both Bracket Pair Colorizer 2 and your Vue Syntax Highlight extension
2. Some brackets pair weren't painted.

Before installing Syntax Highlight:

![image](https://user-images.githubusercontent.com/13297000/103467377-1ed98f00-4d57-11eb-8b34-8e5a714cd015.png)

After:

![image](https://user-images.githubusercontent.com/13297000/103467385-3153c880-4d57-11eb-9907-70280fcb02c3.png)

**Comment by eladcandroid** [comment]
@znck Do you have any idea? Maybe related to my comment here https://github.com/znck/vue-developer-experience/issues/137 ?

**Comment by znck** [comment]
Haven't checked yet, will look into this soon.

**Comment by eladcandroid** [comment]
@znck Any update?
