### ISSUE TITLE
[VueDX/TS(17001)] JSX elements cannot have multiple attributes with the same name

### ISSUE THREAD

**Issue by beary** [vuedx/languagetools#142]
**Describe the bug**
When using multiple `radio` type inputs, VueDX/TS prompts that it cannot have multiple attributes with the same name.

**To Reproduce**
https://v3.vuejs.org/guide/forms.html#radio
```vue
<template>
  <div id="v-model-radiobutton">
  <input type="radio" id="one" value="One" v-model="picked" />
  <label for="one">One</label>
  <br />
  <input type="radio" id="two" value="Two" v-model="picked" />
  <label for="two">Two</label>
  <br />
  <span>Picked: {{ picked }}</span>
</div>
</template>

<script lang="ts">
import { defineComponent, ref } from 'vue'

export default defineComponent({
  setup() {
    const picked = ref('')
    return {
      picked
    }
  }
})
</script>

```

**Expected behavior**
No error be reported when using `<input type='radio' ...`

**Screenshots/Recording**
![Screenshot from 2021-01-04 16-07-12](https://user-images.githubusercontent.com/6630583/103514138-01b3d600-4ea7-11eb-8aba-e85254d894bb.png)

**Info (please complete the following information):**
 - Linux x64 5.9.16-1-MANJARO
 - VS Code 1.52.1
 - TypeScript 4.1.3
 - Vue 3.0.5

**Comment by 2256184693** [comment]
Same Error! +1

**Comment by olemarius** [comment]
+1

```
  <select 
                v-model="selectedFont" 
                class="form-control" 
                :required="true" 
                @change="update" 
                @click="loadAllGoogleFonts">
```

clears if I remove either @change or v-model

**Comment by WingDust** [comment]
I have a new example with same error + 1
  ```vue
<input 
  @keydown.ctrl.f="forward"
  @keydown.ctrl.p="previous"
  @keydown.ctrl.n="next"
  @keydown.ctrl.w="killaword"
  @keydown.ctrl.h="backspace"
  @keydown.ctrl.e="end"
  @keydown.enter="enter"
   />
```

**Comment by jgourmelen** [comment]
Same error for me :  
```
        <select
          id="selected"
          v-model="selected"
          v-on:change="deleteListArticle($event)"
        >
          <option value="select">Select</option>
          <option value="deleteAll">Delete All</option>
        </select>

```


The error : 
`
(prop) onChange?: ((payload: Event) => void) | undefined
JSX elements cannot have multiple attributes with the same name.VueDX/TS(17001)
View Problem (⌥F8)
No quick fixes available
`

**Comment by elliottregan** [comment]
I'm seeing the same error with a radio switch. If it helps with debugging, I posted a question to SO before I found this bug report: https://stackoverflow.com/questions/66723391/how-do-i-use-v-model-with-an-object-using-vue-and-typescript

It has my component code in it, and a list of errors.
