### ISSUE TITLE
:class="[]" binding throws (false positive?) on type 'IntrinsicAttributes'

### ISSUE THREAD

**Issue by TheDutchCoder** [vuedx/languagetools#148]
**Describe the bug**
When binding classes with the array syntax like so:
```html
:class="[textClasses, marginClasses]"
```
The plugin throws an error:
```
Type '{ class: string[]; }' is not assignable to type 'IntrinsicAttributes'.
  Property 'class' does not exist on type 'IntrinsicAttributes'.VueDX/TS(2322)
```

**To Reproduce**
1. Add class binding with array syntax
2. See error

**Expected behavior**
The plugin to not throw an error.

**Info (please complete the following information):**
 - OS MacOS 10.15.7
 - IDE VSCode
 - TypeScript Version 3.9.3
 - Vue Version: 3.0.0

**Comment by znck** [comment]
Blocked on https://github.com/vuejs/vue-next/pull/2947

**Comment by EricRabil** [comment]
Here's a `d.ts` merge until it is resolved upstream.

```ts
declare global {
  namespace React {
    interface HTMLAttributes<T> extends AriaAttributes, DOMAttributes<T> {
      class?: unknown;
    }
  }
}
```
