### ISSUE TITLE
Prop is possibly undefined (it's not and it can't be)

### ISSUE THREAD

**Issue by TheDutchCoder** [vuedx/languagetools#154]
**Describe the bug**
When a prop is declared as a Number and is required, it'll throw an error in the template that the prop is possibly undefined.
Event setting a default doesn't help.

**To Reproduce**
1. Declare a prop as a number and as required
2. use the prop in the template
3. See error (it also shows as type `number | undefined`)

**Expected behavior**
Prop type to be correctly inferred.

**Screenshots/Recording**
![image](https://user-images.githubusercontent.com/1668207/104375753-e291f580-54f1-11eb-8390-61a770817ea6.png)

**Info (please complete the following information):**
 - OS MacOS 10.15.7
 - IDE VSCode
 - TypeScript Version 3.9.3
 - Vue Version 3.0.0

**Comment by TheDutchCoder** [comment]
Never mind, space after defineComponent :(

**Comment by znck** [comment]
It should handle spaces.

**Comment by TheDutchCoder** [comment]
Ah ok, didn't know, thanks for re-opening!
