### ISSUE TITLE
Use tsconfig `paths` in vuedx-typecheck.

### ISSUE THREAD

**Issue by maxbogue** [vuedx/languagetools#157]
I manage all the imports in my apps by prefixing with `@`, so `src/foo.ts` becomes `import foo from '@/foo';`. This is defined in my tsconfig.json as `"paths": { "@/*": ["src/*"] },` (as well as in webpack's config). Without supporting this option from tsconfig, vuedx-typecheck is useless to me. Could it be added? It seems like a project so tightly coupled with TypeScript should respect its configuration options. Thanks!

**Comment by znck** [comment]
It should have worked as typecheck uses typescript project to get diagnostics. Could you create a repro for the issue?

**Comment by tony19** [comment]
Also seeing the same issue with a JS project despite `tsconfig.json` workaround with the proper path alias:

<img width="935" alt="Screen Shot 2021-01-15 at 5 24 27 PM" src="https://user-images.githubusercontent.com/26580/104787946-9e535f00-5756-11eb-9ed9-9c1a79a39439.png">


### Steps to reproduce:

 1. Using Vue CLI, create a Vue 2 project with Jest support (no TypeScript):

```
 vue create my-project --default
 cd my-project
 vue add unit-jest
```

 2. In `<root>/tests/unit/example.spec.js`, observe the red squiggly line under the import path in `import HelloWorld from '@/components/HelloWorld.vue'`
 3. Add `<root>/tsconfig.json` that specifies the path alias for `@`:

```json
{
  "compilerOptions": {
    "target": "esnext",
    "module": "esnext",
    "strict": true,
    "jsx": "preserve",
    "importHelpers": true,
    "moduleResolution": "node",
    "experimentalDecorators": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "sourceMap": true,
    "baseUrl": ".",
    "types": [
      "jest"
    ],
    "paths": {
      "@/*": [
        "src/*"
      ]
    },
    "lib": [
      "esnext",
      "dom",
      "dom.iterable",
      "scripthost"
    ]
  },
  "include": [
    "src/**/*.ts",
    "src/**/*.tsx",
    "src/**/*.vue",
    "tests/**/*.ts",
    "tests/**/*.tsx"
  ],
  "exclude": [
    "node_modules"
  ]
}
```

 4. Restart VS Code.
 5. Observe the error has not resolved.


### Environment

 * VS Code 1.52.1
 * VueDX 0.5.0
 * Vue CLI 5.0.0-alpha.2
 * macOS Big Sur 11.1
 * Node 14.9.0
 * npm 6.14.8

**Comment by maxbogue** [comment]
Hmm, in my case it seems I was missing the `.vue` in the import paths for the components that were complaining. Adding that seems to have solved my problem.

**Comment by skyrpex** [comment]
I can reproduce the problem, and the fix provided by https://github.com/znck/vue-developer-experience/issues/157#issuecomment-761731360 worked. Thanks.

**Comment by SimonPrague** [comment]
![Screenshot_2021-bře-20-So_18-13-06](https://user-images.githubusercontent.com/47515740/111878622-f05b6f80-89a7-11eb-8e74-c458f1c73677.png)

I'm struggling with this problem even for `.ts` files.
