### ISSUE TITLE
VSCode extension goes to 100% CPU "randomly"

### ISSUE THREAD

**Issue by TheDutchCoder** [vuedx/languagetools#160]
**Describe the bug**
I haven't been able to pin down the real cause for this, but in the following scenarios `Code Helper (Render)` goes into 100% CPU usage:

1. Whenever I switch git branches (i.e. multiple files change)
2. Whenever I remove a `@click="(e) => doThing(e)"` handler and write a function for it
3. Whenever I import a new component and add it to the template and save

When the extension is disabled it doesn't happen anymore (this is the insider version of VueDX btw).
Let me know if I can help you narrow this down by doing some tests, or provide you with additional info.

Disclaimer: I don't why it happens, but my entire team has the same issue (different hardware/Macs, but same tooling setup)

**To Reproduce**
1. Try one of my examples and see if it happens or not

**Expected behavior**
The extension to not burn up the CPU.

**Info (please complete the following information):**
 - OS MacOS 10.15.7
 - IDE VScode
 - TypeScript Version 3.9.3
 - Vue Version 3.0.0

**Comment by znck** [comment]
I think it is caused by #150 but I'll look into performance soon (will add telemetry to collect some data first).

**Comment by TheDutchCoder** [comment]
I think this doesn't happen anymore for me, feel free to close.
