### ISSUE TITLE
typecheck: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by cawa-93** [vuedx/languagetools#169]
**Describe the bug**
Unable to run typecheck in subdirectory in `raw` format without `--no-pretty`

**To Reproduce**
1. Clone [cawa-93/vite-electron-builder](https://github.com/cawa-93/vite-electron-builder)
2. `git checkout vuedx/typecheck`
3. `npm ci`
4. `npx vuedx-typecheck ./src/main`
4. See error. It tries to read the `vite-electron-builder\index.ts` file instead of reading the `vite-electron-builder\src\main\index.ts` file.

**Logs**
```
$ npx vuedx-typecheck ./src/main

Running for C:\Users\kozac\Dev\vite-electron-builder\src\main
Unexpected error. Please report � https://github.com/znck/vue-developer-experience/issues/new
[Error: ENOENT: no such file or directory, open 'C:\Users\kozac\Dev\vite-electron-builder\index.ts'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\kozac\\Dev\\vite-electron-builder\\index.ts'
}
```

**Info (please complete the following information):**
 - @vuedx/typecheck version 0.6, 0.6.1-insiders-1610911987.0
 - OS Windows
 - TypeScript Version 4.1.3

**Additional context**
With `--no-pretty` work as expected
```
$ npx vuedx-typecheck ./src/main --no-pretty
Running for C:\Users\kozac\Downloads\vite-electron-builder\src\main
index.ts(6,8): error 2322: Type 'string' is not assignable to type 'number'.
index.ts(6,8): suggestion 6133: 'a' is declared but its value is never read.
Found 1 error.
```

**Comment by eratio08** [comment]
This can be fixed by 

`packages/typecheck/src/cli.ts`
```typescript
async function createTextDocument(file: string): Promise<TextDocument> {
  const content = await FSP.readFile(Path.resolve(directory, file), { encoding: 'utf-8' })
  const fileName = toNormalizedPath(file)
  const document = TextDocument.create(
    fileName,
    Path.posix.extname(file),
    0,
    content,
  )

  cache.set(fileName, document)

  return document
}
```
