### ISSUE TITLE
[VueDX/TS(2322)] Input type="number" & type="checkbox" checks for string

### ISSUE THREAD

**Issue by RobbinBaauw** [vuedx/languagetools#172]
**Describe the bug**
When using a `<input type="number" />`, and pass a `number`  to `v-model`, you'll receive an error: ` Type 'string' is not assignable to type 'number'.`. The same goes for checkboxes.

I assume this is because [`InputHTMLAttributes`](https://github.com/vuejs/vue-next/blob/e894caf7315bc36ea30a2fba3f1263025cb9deb0/packages/runtime-dom/types/jsx.d.ts#L494) has the following type for `value`:
```ts
value?: string | string[] | number
```

However, [MDN states](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number#value) that its value is a `Number`. [Checkboxes](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox#value) are a bit more complicated, but `boolean` is not even part of the union found in Vue (so is probably also a bug in Vue).

This probably means some special cases should be handled for VueDX, or each type of input should have their own type definitions in Vue.

**To Reproduce**
1. Clone https://github.com/RobbinBaauw/vue-dx-172
2. Run `yarn dev` to see that we indeed get numbers & booleans
3. Run `yarn build` to see the build fail

**Expected behavior**
Build does not fail.

**Info (please complete the following information):**
 - OS [e.g. Windows/Mac/Linux] - Linux
 - IDE [e.g. VS Code, vim] - Intellij
 - TypeScript Version [e.g. 4.0.1] - 4.1.3
 - Vue Version - 3.0.5

**Additional context**
<details>
<summary>Click to expand logs</summary>

```
src/App.vue:3:34 - error VueDX/TS2322: Type 'string' is not assignable to type 'number'.
 1 | <template>
 2 |   <input type="number" v-model="myNumber" />
   |                                 ~~~~~~~~
 3 |   <input type="checkbox" v-model="myCheckbox" />
 4 | </template>

src/App.vue:4:36 - error VueDX/TS2322: Type 'boolean' is not assignable to type 'string | number | string[] | undefined'.
 1 | <template>
 2 |   <input type="number" v-model="myNumber" />
 3 |   <input type="checkbox" v-model="myCheckbox" />
   |                                   ~~~~~
 4 | </template>
 5 | 
    node_modules/@vue/runtime-dom/dist/runtime-dom.d.ts:588:4
 589 | }
 590 | 
 591 | export interface KeygenHTMLAttributes extends HTMLAttributes {
     |                             ~~~~~
 592 |   autofocus?: boolean
 593 |   challenge?: string
    The expected type comes from property 'value' which is declared here on type 'ElementAttrs<InputHTMLAttributes>'

src/App.vue:4:36 - error VueDX/TS2322: Type 'string' is not assignable to type 'boolean'.
 1 | <template>
 2 |   <input type="number" v-model="myNumber" />
 3 |   <input type="checkbox" v-model="myCheckbox" />
   |                                   ~~~~~~~~~~
 4 | </template>
 5 | 
```
</details>

**Comment by znck** [comment]
It supports `v-model` with `number` modifier. https://v3.vuejs.org/api/directives.html#v-model

**Comment by Eitz** [comment]
Any way to resolve the problem with checkbox+boolean type?

**Comment by PePoDev** [comment]
```sh
yarn create @vitejs/app my-vue-app --template vue-ts
cd my-vue-app
yarn install
yarn run build
```
and Voilà, It  `Error !`

**Comment by frck006** [comment]
@PePoDev : Not really, I have just create the project as you and here the log:

PS C:\Franck\cgid\vuejs3\vite> yarn create @vitejs/app vite02 --template vue-ts
yarn create v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.11: The platform "win32" is incompatible with this module.
info "fsevents@1.2.11" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Installed "@vitejs/create-app@1.7.0" with binaries:
      - create-app
      - cva
Scaffolding project in C:\Franck\cgid\vuejs3\vite\vite02...

Done. Now run:

  cd vite02
  npm install (or `yarn`)
  npm run dev (or `yarn dev`)

Done in 10.72s.
PS C:\Franck\cgid\vuejs3\vite> cd .\vite02\
PS C:\Franck\cgid\vuejs3\vite\vite02> yarn
yarn install v1.22.10
warning package.json: No license field
info No lockfile found.
warning vite02@0.0.0: No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.3.2: The platform "win32" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
Done in 27.09s.
PS C:\Franck\cgid\vuejs3\vite\vite02> yarn build
yarn run v1.22.10
warning package.json: No license field
$ vuedx-typecheck . && vite build
Running for C:\Franck\cgid\vuejs3\vite\vite02
src/components/HelloWorld.vue:6:38 - error VueDX/TS2322: Type 'boolean' is not assignable to type 'string | number | string[] | undefined'.
 3 |
 4 |   <label>
 5 |     <input type="checkbox" v-model="useScriptSetup" /> Use
   |                                     ~~~~~
 6 |     <code>&lt;script setup&gt;</code>
 7 |   </label>
    node_modules/@vue/runtime-dom/dist/runtime-dom.d.ts:588:4
 589 | }
 590 |
 591 | export interface KeygenHTMLAttributes extends HTMLAttributes {
     |                             ~~~~~
 592 |   autofocus?: boolean
 593 |   challenge?: string
    The expected type comes from property 'value' which is declared here on type 'ElementAttrs<InputHTMLAttributes>'

src/components/HelloWorld.vue:6:38 - error VueDX/TS2322: Type 'string' is not assignable to type 'boolean'.
 3 |
 4 |   <label>
 5 |     <input type="checkbox" v-model="useScriptSetup" /> Use
   |                                     ~~~~~~~~~~~~~~
 6 |     <code>&lt;script setup&gt;</code>
 7 |   </label>

src/components/HelloWorld.vue:10:38 - error VueDX/TS2322: Type 'boolean' is not assignable to type 'string | number | string[] | undefined'.
 7 |   </label>
 8 |   <label>
 9 |     <input type="checkbox" v-model="useTsPlugin" /> Provide types for
   |                                     ~~~~~
10 |     <code>*.vue</code> imports
11 |   </label>
    node_modules/@vue/runtime-dom/dist/runtime-dom.d.ts:588:4
 589 | }
 590 |
 591 | export interface KeygenHTMLAttributes extends HTMLAttributes {
     |                             ~~~~~
 592 |   autofocus?: boolean
 593 |   challenge?: string
    The expected type comes from property 'value' which is declared here on type 'ElementAttrs<InputHTMLAttributes>'

src/components/HelloWorld.vue:10:38 - error VueDX/TS2322: Type 'string' is not assignable to type 'boolean'.
 7 |   </label>
 8 |   <label>
 9 |     <input type="checkbox" v-model="useTsPlugin" /> Provide types for
   |                                     ~~~~~~~~~~~
10 |     <code>*.vue</code> imports
11 |   </label>

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by PePoDev** [comment]
@frck006 I'm Following @znck comment
> It supports `v-model` with `number` modifier. https://v3.vuejs.org/api/directives.html#v-model

Then I have fixed by change `ref(true)` -> `ref("true")` in `HelloWorld.vue` all line with type Boolean, And yes It work !.
This is temporary solution and I don't have a better idea because I'm not good in Js and Ts. But this make me continue to setup pipeline.

**Comment by frck006** [comment]
@PePoDev ; Thank you, it's ok.

**Comment by rangermeier** [comment]
> Then I have fixed by change `ref(true)` -> `ref("true")` in `HelloWorld.vue` all line with type Boolean

This workaround doesn't work if you want to initialize with a *false* boolean: `ref("false")` will produce a *truthy* value, i.e. the checkbox would be checked.

**Comment by frck006** [comment]
Cool, thank you @rangermeier

**Comment by ptibbetts** [comment]
I'm seeing two different messages for the same thing in the Vite vue-ts template.

The two `v-model`s inside of [HelloWorld.vue](https://github.com/vitejs/vite/blob/589b29596e8046122b1ad8b69c4c70aa40cd4165/packages/create-app/template-vue-ts/src/components/HelloWorld.vue) display:

```
Type 'string' is not assignable to type 'boolean'.VueDX/TS(2322)
```

as well as

```
Type 'boolean' is not assignable to type 'string | number | string[] | undefined'.VueDX/TS(2322) 
runtime-dom.d.ts(587, 3): The expected type comes from property 'value' which is declared here on type 'ElementAttrs<InputHTMLAttributes>`
```

which confirms @RobbinBaauw 's assumption about `InputHTMLAttributes`.

**Comment by murphybob** [comment]
Surprisingly this is a blocker for me.  My first thought was to try overriding the declaration of `InputHTMLAttributes` provided by `runtime-dom.d.ts` to add `boolean` to the union type for `value`, however unless I'm mistaken that is not possible in typescript.  Even when I did this as a temporary hack in my local `runtime-dom.d.ts` it only fixed the warning on pssing the radio`:value`, but did not help with the `v-model` declaration.

I also couldn't find an equivalent of `// @ts-ignore` to use within the template 🤷  I've had to ditch the plugin for the time being but will keep a close eye on this issue as when it's working it's great! 👍

**Comment by MartinMa** [comment]
The [Vue 3 documentation](https://v3.vuejs.org/guide/forms.html#basic-usage) states that `v-model` on checkboxes and radio buttons uses the `checked` property and the `change` event instead of the `value` property and the `input` event compared to normal text inputs.

The `value` property serves a [different purpose on checkboxes](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox#value). The `checked` property is a `boolean` after all.

So when binding to `v-model` on an input of type `checkbox` (or `radio`) VueDX should probably perform a typecheck on the `checked` property and not on the `value` property (which seems to be happening now).

Looking at the code however it seems that this is already happening. Look at `isCheckboxOrRadio`. So I don't know where to look anymore? Or does this snippet only apply to JSX/TSX?

https://github.com/znck/vue-developer-experience/blob/084c05551c109ae8d2534b60b28a2e257135ad8c/packages/compiler-tsx/src/transforms/transformElement.ts#L362-L374

As a **workaround**:

Instead of this:
```html
<input type="checkbox" v-model="isChecked" />
```

You can do this:
```html
<input type="checkbox" :checked="isChecked" @change="onChange($event)" />
```
```ts
// Add this to your methods
onChange(event: Event): void {
  this.isChecked = (event?.target as HTMLInputElement).checked
}
```

Yes it is cumbersome.

**Comment by AlansCodeLog** [comment]
Is there no way to do something like `// @ts-expect-error` in templates? I can't find anything regarding this except that eslint comments supposedly work.

Also a shorter way to do this is to just lie.

For simple checkboxes you can get away with:
```ts
const value = ref<string>(false as any as string)
```
If you need to set the value a lot:
```ts
const FALSE = false as any as string
const TRUE = true as any as string
const value = ref<string>(FALSE)
value.value = TRUE
// if you need them in the template:
return {value, TRUE, FALSE}
```
