### ISSUE TITLE
Incorrect errors when using with vue-class-component

### ISSUE THREAD

**Issue by graup** [vuedx/languagetools#189]
**Describe the bug**
I'm not sure if this issue should be here or in the vue-class-component repo. Anyway, I migrated some fairly simple code from vue 2 to vue 3 using the available guides. I created a new project from scratch with vite and then ported my components. 

When running `yarn build` I get a bunch of incorrect errors from `vuedx-typecheck`:

- [src/components/Roulette.vue:12:21](https://github.com/graup/roulette-choice/blob/vue3/src/components/Roulette.vue) `- error VueDX/TS2339: Property 'index' does not exist on type 'string'.`
Wrong. `slice` isn't of type `string`. No idea where it got that from.

- A bunch of errors regarding svg syntax. It looks like it doesn't like SVG?

- [src/App.vue:5:9](https://github.com/graup/roulette-choice/blob/vue3/src/App.vue) ` - warning VueDX59002: The component 'Roulette' is inferred as global component. It may not be available at runtime.`
Wrong. I included it in the vue-class-component options.

**To Reproduce**
[git clone -b vue3 https://github.com/graup/roulette-choice](https://github.com/graup/roulette-choice/tree/vue3)
Run `yarn` and `yarn build`

**Expected behavior**
This code builds fine when using `yarn dev` and shows no errors in VSCode.

**Comment by graup** [comment]
Pinging @ktsn – are these vue-class-component issues?

**Comment by znck** [comment]
Class component is not supported yet.

**Comment by chernikov-v** [comment]
> Class component is not supported yet.

Is there a plan to support it?
