### ISSUE TITLE
Components not recognised in VSCode IDE

### ISSUE THREAD

**Issue by basvdijk** [vuedx/languagetools#192]
**Describe the bug**
Imported components are not detected

**To Reproduce**
1.  checkout [https://github.com/primefaces/primevue-quickstart](https://github.com/primefaces/primevue-quickstart)
2. run npm i
3. open in vscode

The components are not recognised:
![image](https://user-images.githubusercontent.com/644550/106773182-15d32a80-6641-11eb-9fbb-edb9928ce857.png)

**Expected behavior**
That the components don't give an error

**Info (please complete the following information):**
 - Mac
 - VScode
 - Vue 3.0.3

**Comment by GitHdu** [comment]
have not resolved yet
