### ISSUE TITLE
Option to disable "inferred as global component" warning

### ISSUE THREAD

**Issue by richardtallent** [vuedx/languagetools#197]
**Is your feature request related to a problem? Please describe.**
I have a number of globally-registered components, and I do this quite on purpose. VueDX is throwing warnings because of this, and there does not appear to be a way to disable this metric. Global registration of components is not always appropriate, but it should not always result in a warning.

**Describe the solution you'd like**
An option to disable this rule, and documentation for how to use the option.

**Describe alternatives you've considered**
Registering components locally is an alternative, but is untenable due to the number of potential code changes this would require.

**Comment by olemarius** [comment]
Just spent a few hours trying to get rid of this warning. Would be great to be able to supress the warning.

**Comment by znck** [comment]
You can configure global components using vueconfig.json. Ex. https://github.com/znck/vue-developer-experience/blob/main/samples/feature-vue-project-configured/vueconfig.json

**Comment by merceyz** [comment]
I also ran into this and looked at the samples folder to find that config, I specified it to include `vuetify` and the warnings were gone and it autocompletes the vuetify components but not their attributes

**Comment by znck** [comment]
Attribute completion depends on type definitions but it will support web types soon.

**Comment by vegerot** [comment]
> I also ran into this and looked at the samples folder to find that config, I specified it to include `vuetify` and the warnings were gone and it autocompletes the vuetify components but not their attributes

How do you specify `vueconfig.json` to include `vuetify`?

**Comment by merceyz** [comment]
I created a `vueconfig.json` in the root containing
```json
{
	"globalComponents": ["vuetify"]
}
```

**Comment by webliving** [comment]
The component 'van-circle' is inferred as global component. It may not be available at runtime.VueDX(59002)
