### ISSUE TITLE
Multiple checkboxes bound to the same array triggers VueDX/TS17001

### ISSUE THREAD

**Issue by simon04** [vuedx/languagetools#198]
**Describe the bug**

The example "Multiple checkboxes, bound to the same array" from https://v3.vuejs.org/guide/forms.html#checkbox triggers `VueDX/TS17001: JSX elements cannot have multiple attributes with the same name.`

**To Reproduce**
Run `vuedx-typecheck` on the following snippet distilled from https://v3.vuejs.org/guide/forms.html#checkbox

```vue
<template>
  <div id="v-model-multiple-checkboxes">
    <input type="checkbox" id="jack" value="Jack" v-model="checkedNames" />
    <label for="jack">Jack</label>
    <input type="checkbox" id="john" value="John" v-model="checkedNames" />
    <label for="john">John</label>
    <input type="checkbox" id="mike" value="Mike" v-model="checkedNames" />
    <label for="mike">Mike</label>
    <br />
    <span>Checked names: {{ checkedNames }}</span>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";
export default defineComponent({
  data() {
    return {
      checkedNames: [],
    };
  },
});
</script>
```

**Expected behavior**
The snippet should not trigger `VueDX/TS17001: JSX elements cannot have multiple attributes with the same name.`

**Info (please complete the following information):**
Vue.js 3.0.5

**Comment by elliottregan** [comment]
I get this as well, with a radio switch.

**Comment by elliottregan** [comment]
If it helps with debugging, I posted a question to SO with my markup and a list of errors: https://stackoverflow.com/questions/66723391/how-do-i-use-v-model-with-an-object-using-vue-and-typescript

**Comment by elliottregan** [comment]
This bug has been around for a while, too: https://github.com/znck/vue-developer-experience/issues/142

**Comment by areve** [comment]
I can't find anyway to suppress this error, or downgrade it to a warning. Is that possible?
