### ISSUE TITLE
error VueDX/TS: context.imports.add is not a function

### ISSUE THREAD

**Issue by xon52** [vuedx/languagetools#208]
**Describe the bug**
Normal build throws an error in my normal src folder. Was working fine a few days ago, but ghost in the machine.

**To Reproduce**
1. Try build any vue file with a `<template>`

**Expected behavior**
No error.

**Screenshots/Recording**
![image](https://user-images.githubusercontent.com/30713944/109141597-a2d55380-77a9-11eb-8396-1d34c4518762.png)
```html
<!-- Test.vue -->
<template>
  <p></p>
</template>
```

**Info (please complete the following information):**
```
VSCode Version: 1.53.2 (user setup)
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:48:04.245Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.18363
```

**Additional context**
```js
// package.json
{
  "name": "test",
  "version": "1.0.0",
  "types": "./dist/main.d.ts",
  "module": "./dist/test.es.js",
  "files": [
    "dist"
  ],
  "scripts": {
    "build:lib": "vuedx-typecheck . && vite build && tsc --emitDeclarationOnly",
  },
  "devDependencies": {
    "@types/googlemaps": "^3.43.3",
    "@vitejs/plugin-vue": "^1.1.4",
    "@vue/compiler-sfc": "^3.0.5",
    "@vuedx/typecheck": "^0.6.0",
    "@vuedx/typescript-plugin-vue": "^0.6.0",
    "sass": "^1.32.8",
    "typescript": "^4.1.3",
    "vite": "^2.0.0-beta.70",
    "vue": "^3.0.5"
  }
}
```

```js
// tsconfig.json
{
  "compilerOptions": {
    "target": "esnext",
    "module": "esnext",
    "moduleResolution": "node",
    "strict": true,
    "jsx": "preserve",
    "sourceMap": true,
    "resolveJsonModule": true,
    "esModuleInterop": true,
    "lib": [
      "esnext",
      "dom"
    ],
    "types": [
      "vite/client"
    ],
    "plugins": [
      {
        "name": "@vuedx/typescript-plugin-vue"
      }
    ],
    "declaration": true,
    "emitDeclarationOnly": true,
    "outDir": "./dist"
  },
  "include": [
    "src"
  ]
}
```

**Comment by SimonPrague** [comment]
I'\m having the same problem :(

**Comment by ifzm** [comment]
I'\m having the same problem :(

**Comment by SimonPrague** [comment]
Is there a temporary workaround?

**Comment by xon52** [comment]
I just had to disable it for that build. It's annoying as it actually builds another part of the same project fine, but I don't have more time to spend on doing tests right now.

**Comment by SimonPrague** [comment]
How do you disable it?

**Comment by xon52** [comment]
> How do you disable it?

In your package.json:
`"build": "vuedx-typecheck . && vite build && tsc"`
Change to:
`"build": "vite build && tsc"`

**Comment by SimonPrague** [comment]
Oh, thanks a lot!

**Comment by lukashass** [comment]
For me this first occurred when `@vue/compiler-core` was updated to `3.0.6`. So downgrading to `3.0.5` is a possible workaround.

Looking at the commits it seems like the culprit is this one: https://github.com/vuejs/vue-next/commit/c69f4ea857b7db8d26bbde2f80786c8212d16770#diff-ed0d861d15952e0e6eb72faeeb444ef4a2325d22d7e5013653307dbe23a496a1

**Comment by webszy** [comment]
It seems not totally reslove this problem,i just deleted the vuedx-typecheck when i build,why this issue closed?
