### ISSUE TITLE
VueDX seems not working at all in VS Code

### ISSUE THREAD

**Issue by arturfityka** [vuedx/languagetools#219]
**Describe the bug**
VueDX doesn't recognize `.vue` extension. VS Code still displays "Plain Text" in such files. The entire code is in single color.

**To Reproduce**
I have completely fresh VS Code installation with only VueDX plugin installed.

**Info (please complete the following information):**
 - Windows 10
 - VS Code 1.54.1
 - TypeScript Version 4.2.2
 - Vue Version ^3.0.0
 - Other versions (e.g. Nuxt, Vue Router etc.)

**Additional context**
I've checked it with [this code](https://github.com/Code-Pop/Real-World-Vue-3-TypeScript/tree/06-begin) and with fresh Vue project as well (`vue create` in CLI).

**Comment by zynth17** [comment]
have you try reloading your vscode?

**Comment by arturfityka** [comment]
Multiple times, I've even reinstalled the vscode.

**Comment by zynth17** [comment]
have you try combining vuedx with vetur? it works well for me

**Comment by arturfityka** [comment]
It's better with Vetur. At least I got the syntax highlighting. However, I feel only Vetur works now. How can I check if VueDX is working?

**Comment by manast** [comment]
Same problem here, using vs code 1.59 on Mac OS 11.4. No syntax highlighting however there is syntax checks. Looks like this:

![image](https://user-images.githubusercontent.com/95200/128696607-5f9f7bb8-b105-403b-ac69-f7309da8300c.png)


![image](https://user-images.githubusercontent.com/95200/128696653-27c80927-35f8-40e4-a3cd-b7f8bff11aaa.png)


and so on...
