### ISSUE TITLE
Global Components Unrecognized (Vue 3 + Typescript)

### ISSUE THREAD

**Issue by wffranco** [vuedx/languagetools#221]
I set some global components, import then at different ways (a global file that import all, using require, and directly into main, like you can see in the picture:
![image](https://user-images.githubusercontent.com/1977287/110894881-b236bf80-82c6-11eb-8a3e-d17577eb45a8.png)

But no matter how I import it, never find the global components.
![image](https://user-images.githubusercontent.com/1977287/110895218-4e60c680-82c7-11eb-936f-397cb7e6e7ff.png)

I suppose that work with vue 2, but not with vue 3.

**Comment by WingDust** [comment]
+1

**Comment by WumaCoder** [comment]
+1

**Comment by gekkedev** [comment]
I believe [this](https://github.com/znck/vue-developer-experience/blob/main/packages/projectconfig/src/index.ts) is what you're looking for? If you place a file named `vueconfig.json` in your project root and start editing it, VSCode will know which options to suggest. There is an option called `globalComponents` but unfortunately, I cannot find not much documentation on this whole file.
