### ISSUE TITLE
The component is inferred as global component & JSX element type Error

### ISSUE THREAD

**Issue by webliving** [vuedx/languagetools#226]
**Describe the bug**
JSX element type 'VanCircle' does not have any construct or call signatures.VueDX/TS(2604)
The component 'van-circle' is inferred as global component. It may not be available at runtime.VueDX(59002)

**To Reproduce**

**Expected behavior**
no typescript Error 

**Screenshots/Recording**
![image](https://user-images.githubusercontent.com/3808577/115980924-e4745600-a5c2-11eb-8d39-4172c0d98ac9.png)
**Info (please complete the following information):**
 - OS Mac
 - IDE VS Code
 - TypeScript Version 4.2.4
 - Vue Version 3.0.0

**Additional context**
Add any other context about the problem here e.g. code snippets or reproduction repository etc.

**Comment by avtion** [comment]
i have the same question....

<img width="711" alt="截屏2021-04-28 23 07 10" src="https://user-images.githubusercontent.com/34846850/116427288-be37fb80-a7f8-11eb-9df7-096f5b2cc9a6.png">

**Comment by xon52** [comment]
Same issue while using [Element+ component library](https://element-plus.org/).
![image](https://user-images.githubusercontent.com/30713944/125796213-bab6bf59-62d9-4bcf-9c59-8b784335f7f5.png)

**Comment by Zonciu** [comment]
Same issue in Quasar project.

![image](https://user-images.githubusercontent.com/10374056/126073865-c4945b22-9aa3-4105-a1df-a085919e4acb.png)

**Comment by RyanHavoc** [comment]
I'm having the same issue as well, but I'm using Vue (not React) and it's flagging `<component>` with this warning:

```
JSX element type '_DyComp0_' does not have any construct or call signatures.VueDX/TS(2604)
```

![image](https://user-images.githubusercontent.com/824169/143309447-636f23ae-414c-49ce-ad31-5c182f946b9f.png)

**Comment by BinarySpike** [comment]
I'm having the same issue with Quasar.  However, registered components are errorless.

![image](https://user-images.githubusercontent.com/2881351/162857189-5892fa81-c5ad-4481-b2da-545021a2ac01.png)
