### ISSUE TITLE
The import .vue in the .vue file is located as 3 modules, same file but in different scopes

### ISSUE THREAD

**Issue by masquevil** [vuedx/languagetools#227]
**Describe the bug**
#### Bug 2
The import `.vue` file in the `.vue` file can be located, but 3 modules will be found, which are the same file but in different scopes:

Found 2 modules when click component name：
![Found 2 modules when click name](https://user-images.githubusercontent.com/3344691/121859102-e4264a80-cd29-11eb-82fd-02fd73c75015.png)
Found 2 modules when click component file path：
![Found 2 modules when click path](https://user-images.githubusercontent.com/3344691/116193034-4b2f7600-a761-11eb-9eaa-11d1eacaf7b9.png)

Click the first one to enter, all the contents in the `<script>` tag will be selected:
![selected area 1](https://user-images.githubusercontent.com/3344691/116193089-64d0bd80-a761-11eb-9d68-8fde03688a8f.png)

Click the second one to enter, it will select the `defineComponent`:
![selected area 2](https://user-images.githubusercontent.com/3344691/121858657-6b26f300-cd29-11eb-9e57-02d82759421b.png)

Click the third one to enter, it will select from the `<script>` tag to the end of the file:
![selected area 2](https://user-images.githubusercontent.com/3344691/116193188-8b8ef400-a761-11eb-918f-0441d40ba0f4.png)

#### Bug 3
```js
import Comp from './xxx/yyy'
```
If you do not write `.vue` or `index.vue`, the corresponding file cannot be recognized.

#### Bug 1
<del>In the vscode editor, if you import a `.vue` file in a `.ts` or `.js` file, you will not be able to locate the file, only `shims-vue.d.ts`.
But there is no problem importing the `.vue` file in the `.vue` file：</del>

<del>Note that there is no entry.vue file in the dropbox:
https://user-images.githubusercontent.com/3344691/116192094-f4756c80-a75f-11eb-9393-ca88cebe2982.png</del>

<del>command + click to jump, it will jump to `shims-vue.d.ts`:
https://user-images.githubusercontent.com/3344691/116192835-fc81dc00-a760-11eb-8d90-74a0534ccf95.png</del>

**To Reproduce**
https://github.com/masquevil/stock

**Info (please complete the following information):**
```node
  System:
    OS: macOS 11.0.1
    CPU: (4) x64 Intel(R) Core(TM) i7-4650U CPU @ 1.70GHz
    Memory: 415.90 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.14.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.11.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 90.0.4430.93
    Firefox: 72.0.2
    Safari: 14.0.1
  npmPackages:
    @vitejs/plugin-vue: ^1.2.1 => 1.2.1 
    vite: ^2.1.5 => 2.1.5 
```

**Comment by masquevil** [comment]
Anybody here?

**Comment by znck** [comment]
On a break. Will be back next month.

**Comment by masquevil** [comment]
Bug 1 have been fixed by follow https://github.com/vuejs/vetur/issues/2016
Bug 2&3 still exists
