### ISSUE TITLE
Support Takeover mode

### ISSUE THREAD

**Issue by danielelkington** [vuedx/languagetools#267]
The official Vue docs recommend [using Takeover Mode](https://vuejs.org/guide/typescript/overview.html#takeover-mode) when using TypeScript and Volar to improve performance. However when using Takeover Mode, VueDX is automatically disabled as it depends on the built-in "TypeScript and JavaScript Language Features" extension that must be disabled to allow Takeover Mode.
![image](https://user-images.githubusercontent.com/20923693/159828536-aacfc2d7-11bb-4ee9-83d9-70aceff928cc.png)

Can VueDX support Takeover Mode? Alternatively if this isn't possible could a note be added to the README advising that Takeover Mode cannot be used if using Volar?

**Comment by znck** [comment]
VueDX is an alternative to Volar. They key difference being:

- Volar is implemented using language server protocol and it runs an embedded TypeScript language server. 
- VueDX is implemented as a TypeScript server plugin and it enhances already running TypeScript server (in builtin TypeScript extension).

**Comment by danielelkington** [comment]
Thanks @znck for the reply. I tried disabling Volar and just using VueDX in VS Code, however this results in no syntax highlighting in .vue files (same as https://github.com/vuedx/languagetools/issues/219). Is it really possible to use VueDX on its own, without Vetur/Volar?

**Comment by znck** [comment]
Use https://marketplace.visualstudio.com/items?itemName=znck.vue for syntax highlighting.

**Comment by danielelkington** [comment]
Thanks; all working now. Recommend adding a note to the docs about this project's relationship with Volar to avoid confusion 😃
