### ISSUE TITLE
VueDX crashes on new Nuxt 3 project

### ISSUE THREAD

**Issue by iKnowMagic** [vuedx/languagetools#310]
**Describe the bug**
VueDX crashes on new Nuxt 3 project

**To Reproduce**

1. Create a Nuxt project with `npx nuxi init nuxt-app`
2. Run `yarn install` inside the project's directory
3. Run `yarn nuxi typecheck` inside the project's directory
4. Install eslint with `yarn add eslint -D`
5. Initialize eslint with `yarn eslint --init`

eslint questions / answers
```
? How would you like to use ESLint? … 
❯ To check syntax, find problems, and enforce code style

? What type of modules does your project use? … 
❯ JavaScript modules (import/export)

? Which framework does your project use? … 
❯ Vue.js

Does your project use TypeScript? › Yes

? Where does your code run? …
✔ Node

? How would you like to define a style for your project? … 
❯ Use a popular style guide

? Which style guide do you want to follow? … 
❯ Standard

? What format do you want your config file to be in? … 
❯ JavaScript

The config that you've selected requires the following dependencies:
....
? Would you like to install them now? › Yes

? Which package manager do you want to use? … 
❯ yarn
```
6. Open `app.vue` and save the file

<img width="665" alt="image" src="https://user-images.githubusercontent.com/8712362/200351724-51f0195e-fe0f-4ccc-876b-d2b6405a5470.png">

**Expected behavior**
VueDX should work and the error should not appear.

**Info (please complete the following information):**
MacOS with Nuxt 3

**Comment by znck** [comment]
I cannot reproduce it. Does this happen only in nuxt project?
