### ISSUE TITLE
Hi, I'm curious about the font usded in VS code extension introduction page

### ISSUE THREAD

**Issue by Microdeep-ZL** [vuedx/languagetools#320]
Hi, I was impressed by the font when I happened to see your [Vue extension](https://marketplace.visualstudio.com/items?itemName=znck.vue) in VS Code. May I know what font face it is? Thank you so much! :smiley:

![image](https://raw.githubusercontent.com/znck/vue-developer-experience/main/extensions/vscode-vue/demo/FencedCodeBlock-Vue.png)

**Comment by znck** [comment]
Been away for a while, FiraCode (https://github.com/tonsky/FiraCode).

**Comment by Microdeep-ZL** [comment]
Great, thanks for your reply!

**Comment by Microdeep-ZL** [comment]
Sorry to interrupt, I found the font in the picture should be [Operator Mono](https://www.whatfontis.com/OTH_Operator-Mono-Office-Regular.font?text=scriptexport#ct)
Thanks again!
