### ISSUE TITLE
vue 文件中的<style>标签中无法正确注释

### ISSUE THREAD

**Issue by lfire** [vuedx/languagetools#326]
Type: <b>Bug</b>

打开.vue文件，在<style></style>中，行注释某一行样式，其注释格式为html格式（），无法正确以 （//）格式注释

Extension version: 0.12.0
VS Code version: Code 1.87.2 (Universal) (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:21:31.043Z)
OS version: Darwin x64 23.4.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|95, 55, 36|
|Memory (System)|16.00GB (0.37GB free)|
|Process Argv|. --enable-proposed-api Tencent-Cloud.coding-copilot --crash-reporter-id 090e8794-94c0-4e16-92c5-54d1c794490b|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp1r3:30993539
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
g1icg217:30999571

```

</details>

**Comment by Alan3344** [comment]
The znk.vue plug-in cannot correctly handle the comments on the shortcut keys in the style tag part of the Vue component

I didn't have this problem at first. Later I discovered the problem through binary search.

Select part of the code of the css block
Press `Ctrl+/` - Code block comment shortcut keys

Wrong posture:
```css
<!-- input {
  font-family: Consolas, Monaco, "Liberation Mono", Menlo, Courier, monospace;
} -->
```
Correct posture:
```css
body {
  /*scrollbar-color: #c1c1c1 #f0f0f0;
  overflow: hidden;*/
}
```

<details>
<summary>Full code reference: <code>...\src\App.vue</code></summary>

```vue
<script setup>
import Input from './components/Input.vue';
</script>

<template>
  <Input />
</template>

<style>
.el-textarea__inner {
  font-family: Consolas, Monaco, "Liberation Mono", Menlo, Courier, monospace;
}

<!-- input {
  font-family: Consolas, Monaco, "Liberation Mono", Menlo, Courier, monospace;
} -->

body {
  /*scrollbar-color: #c1c1c1 #f0f0f0;
  overflow: hidden;*/
}
</style>
```

![image](https://github.com/vuedx/languagetools/assets/60773912/c1ba7aa2-9d26-4dd5-bddb-a3519b95b34e)
</details>
