### ISSUE TITLE
Enable code formatting for vue files

### ISSUE THREAD

**Issue by pikax** [vuedx/languagetools#34]
Format the code with CTRL+SHIFT+F (or MaxOS equivalent)

**Comment by znck** [comment]
Scope of formatting .vue files is pretty wide, I feel should limit formatting `<script>` blocks and order of blocks in SFC (intuitively TS plugin should have better performance with <script> blocks at the top)

**Comment by pikax** [comment]
We could take the same approach as the vetur which allows to choose which formatter for `<template>`

**Comment by znck** [comment]
But we don't have access to formatters as TS plugin doesn't know if it is running in IDE (or which IDE).

Possibly, We can embed prettier and use TS format option to configure it.

**Comment by pikax** [comment]
the auto-formatting would only be available on the vscode extension. 

Without prettier, my code looks ugly 😄
