### ISSUE TITLE
@vuedx/typecheck error on component emits

### ISSUE THREAD

**Issue by cexbrayat** [vuedx/languagetools#82]
Using `0.3.1-insiders-1606311019.0`

Given a component that emits an event `wave` (properly declared with `emits`), than vuedx throws:

```
./src/App.vue
=============
=> ./src/App.vue:3:62
Error :: Type '{ msg: string; onWave: () => boolean; }' is not assignable to type 'IntrinsicAttributes & Partial<{}> & Pick<Readonly<{} & { msg?: string | undefined; }> & VNodeProps & AllowedComponentProps & ComponentCustomProps, "msg" | ... 9 more ... | "style">'.
      -> Property 'onWave' does not exist on type 'IntrinsicAttributes & Partial<{}> & Pick<Readonly<{} & { msg?: string | undefined; }> & VNodeProps & AllowedComponentProps & ComponentCustomProps, "msg" | ... 9 more ... | "style">'. (code 2322)
   1 | <template>
   2 |   <img alt="Vue logo" src="./assets/logo.png">
   3 |   <HelloWorld msg="Welcome to Your Vue.js + TypeScript App" @wave="waved = true"/>
     |                                                              ^^^^^^
   4 |   {{ waved }}
   5 | </template>
```

with HelloWorld.vue

```ts
export default defineComponent({
  name: 'HelloWorld',
  emits: {
    wave: () => true
  },
  props: {
    msg: String,
  },
  setup(props, { emit }) {
    return {
      wave: () => emit('wave')
    }
  }
});
```

repro: https://github.com/cexbrayat/template-typechecking/pull/7

**Comment by cexbrayat** [comment]
Also note that it throws:

```
=> ./src/components/HelloWorld.vue:43:9
Suggestion :: 'props' is declared but its value is never read. (code 6133)
  41 |     msg: String,
  42 |   },
  43 |   setup(props, { emit }) {
     |         ^^^^^
  44 |     return {
  45 |       wave: () => emit('wave')
```

when it shouldn't?

**Comment by znck** [comment]
You can replace `props` with `_` if you're not using it. It's coming directly from the TS server, I don't want to change this behavior.

**Comment by znck** [comment]
Related/DependsOn: https://github.com/vuejs/vue-next/pull/2164

**Comment by cexbrayat** [comment]
> You can replace `props` with `_` if you're not using it. It's coming directly from the TS server, I don't want to change this behavior.

I should have explained better: the TS config enables  `strict` but not `noUnusedParameters` (I think `noUnusedParameters` is not enabled by `strict` https://www.typescriptlang.org/tsconfig#strict). And this suggestion is shown when `noUnusedParameters` is enabled right?

**Comment by edorgeville** [comment]
Hi @znck, I think your answer addresses the props issue, but not the original emitter issue. I run into the same problem as the original post.
