### ISSUE TITLE
@vuedx/typecheck v-slot typings

### ISSUE THREAD

**Issue by cexbrayat** [vuedx/languagetools#83]
When using v-slot, for example with `RouterView`, `vudex-typecheck` throws:

```
=> ./src/App.vue:4:27
Error :: Binding element 'Component' implicitly has an 'any' type. (code 7031)
   2 |   <Navbar />
   3 |   <div class="container" style="margin-top: 70px">
   4 |     <RouterView v-slot="{ Component }">
```

This obvious fix is to disable `noImplicitAny`, but I was wondering if it was possible to do better?

**Comment by znck** [comment]
Related RFC: https://github.com/vuejs/rfcs/pull/192

**Comment by simon04** [comment]
Vetur fixed tracked this issue https://github.com/vuejs/vetur/issues/2258 and silenced the error in the PR https://github.com/vuejs/vetur/pull/2259.

**Comment by cyrus1996** [comment]
Hello for future reader try : 
   4 |     <RouterView v-slot="{ Component }: { Component: Object }">

This should do the trick, for perfectionnists I think the original value in of VNode instance

**Comment by znck** [comment]
Fixed in https://github.com/vuedx/languagetools/commit/7d1d193ec857a593f2c40ce3c6780e6b38293028
